### ISSUE TITLE
Circular dependency with `beliefmatching`

### ISSUE THREAD

**Issue by MarcSerraPeralta** [quantumgizmos/ldpc#49]
There is a circular dependency with `beliefmatching`. The `pyproject.toml` files in both libraries clearly show that the `ldpc` library requires `beliefmatching` and `beliefmatching` requires the `ldpc` library. 

A simple reproducible example of the issue:

```
virtualenv venv # python 3.10.13
source venv/bin/activate
pip install ldpc
pip install beliefmatching # not needed because ldpc already installs beliefmatching
python -c "import beliefmatching"
```

Error raised during the last command:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/marcserraperal/Downloads/venv/lib/python3.10/site-packages/beliefmatching/__init__.py", line 1, in <module>
    from .belief_matching import *
  File "/Users/marcserraperal/Downloads/venv/lib/python3.10/site-packages/beliefmatching/belief_matching.py", line 4, in <module>
    from ldpc import bp_decoder
  File "/Users/marcserraperal/Downloads/venv/lib/python3.10/site-packages/ldpc/__init__.py", line 9, in <module>
    from ldpc.sinter_decoders import SinterBpOsdDecoder
  File "/Users/marcserraperal/Downloads/venv/lib/python3.10/site-packages/ldpc/sinter_decoders/__init__.py", line 1, in <module>
    from ldpc.sinter_decoders.sinter_bposd_decoder import SinterBpOsdDecoder
  File "/Users/marcserraperal/Downloads/venv/lib/python3.10/site-packages/ldpc/sinter_decoders/sinter_bposd_decoder.py", line 6, in <module>
    from beliefmatching import detector_error_model_to_check_matrices
ImportError: cannot import name 'detector_error_model_to_check_matrices' from partially initialized module 'beliefmatching' (most likely due to a circular import) (/Users/marcserraperal/Downloads/venv/lib/python3.10/site-packages/beliefmatching/__init__.py)
```

Note that the error above is not raised when running `python -c "import ldpc"`. 

I have raised this issue here in the `ldpc` library and not in `beliefmatching` because the circular dependency problem is due to [this commit](https://github.com/quantumgizmos/ldpc/commit/79d5046170798a36de2aa68bd70e3e647b4d245e). 

For anyone struggling with this problem, it can be temporarily solved by installing a version of the `ldpc` library before the linked commit, e.g. `ldpc==0.1.51`.

**Comment by MarcSerraPeralta** [comment]
This issue was also raised in `beliefmatching`, see [here](https://github.com/oscarhiggott/BeliefMatching/issues/1).

**Comment by quantumgizmos** [comment]
Thanks. I've removed beliefmatching as a dependency. Hopefully this fixes the issue.
