### ISSUE TITLE
hgp function broken

### ISSUE THREAD

**Issue by wu-shixin** [quantumgizmos/ldpc#52]
As I tried the  examples from BPOSD repo:
```
from ldpc.codes import rep_code
from bposd.hgp import hgp
h=rep_code(3)
surface_code=hgp(h1=h,h2=h,compute_distance=True) #nb. set compute_distance=False for larger codes
surface_code.test()
```

I got error messages:
```
Traceback (most recent call last):
  File "c:\Users\wu\Documents\research\squint\sim\first.py", line 4, in <module>
    surface_code=hgp(h1=h,h2=h,compute_distance=True) #nb. set compute_distance=False for larger codes
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bposd\hgp.py", line 26, in __init__
    self.m2,self.n2=np.shape(h2)
    ^^^^^^^^^^^^^^^
ValueError: not enough values to unpack (expected 2, got 0)
```

So I tried to put `.toarray()` after rep_code(3), and I got
```
C:\Users\wu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bposd\css.py:114: SparseEfficiencyWarning: Comparing a sparse matrix with a nonzero scalar using != is inefficient, try using == instead.
  pivots=mod2.row_echelon(log_stack.T)[3]
Traceback (most recent call last):
  File "c:\Users\wu\Documents\research\squint\sim\first.py", line 4, in <module>
    surface_code=hgp(h1=h,h2=h,compute_distance=True) #nb. set compute_distance=False for larger codes
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bposd\hgp.py", line 48, in __init__
    self.compute_logicals()
  File "C:\Users\wu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bposd\css.py", line 120, in compute_logicals
    self.lx=compute_lz(self.hz,self.hx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\bposd\css.py", line 114, in compute_lz
    pivots=mod2.row_echelon(log_stack.T)[3]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src_python\\ldpc\\mod2\\_mod2.pyx", line 527, in ldpc.mod2._mod2.row_echelon
  File "C:\Users\wu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\ldpc\mod2\_legacy_v1.py", line 69, in row_echelon
    if the_matrix[pivot_row, col] != 1:
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\wu\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\scipy\sparse\_base.py", line 370, in __bool__
    raise ValueError("The truth value of an array with more than one "
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all().
```

Please help. Thanks.

**Comment by yifanhong** [comment]
Commenting to bring more attention since I am also having the same issue.

**Comment by quantumgizmos** [comment]
Hi

Sorry for slow response. The bposd package has now been updated to support ldpc_v2.

You can install the new version `pip install -U bposd`

Could you test?

Thanks
Joschka
